#! /bin/sh
focused=$(xrdb ~/.Xresrouces -query all | grep color6 | cut -f2 | head -n 1)
normal=$(xrdb ~/.Xresrouces -query all | grep background | cut -f2 | head -n 1)

#Nitrogen
nitrogen --restore 

#set compose key
setxkbmap -option "compose:ralt"

#Polybar 
$HOME/.config/polybar/launch.sh

#Dunst
#dunst &
 
#Picom 
#picom &

#sxhkd 
sxhkd &

#######################################################

#BSPWM-CONFIG
pgrep -x sxhkd > /dev/null 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_radius		15
bspc config focused_border_color	"$focused" 
bspc config normal_border_color   	"$normal"
bspc config border_width		3
bspc config window_gap			8

# Window configuration
bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config single_monocle	false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
